from web.admin.collection import (
    BADGE_GROUP_COLUMN_CELL_CLASS,
    BADGE_GROUP_COLUMN_WIDTH,
    NAME_COLUMN_CELL_CLASS,
    NAME_COLUMN_WIDTH,
    AdminCollectionSpec,
    CardLayout,
    ComponentPlacement,
    ListColumn,
    ListLayout,
)
from web.admin.label import _


COLLECTION_SPEC: AdminCollectionSpec = AdminCollectionSpec(
    key='events',
    components_template='/admin/index/event_components.j2',
    item_id_attribute='uniq_id',
    card_href_component='row_href',
    row_href_component='row_href',
    card=CardLayout(
        summary_class='justify-content-center',
        header=(ComponentPlacement('identity', 'flex-grow-1 min-width-0'),),
        summary=(
            ComponentPlacement('date_range'),
            ComponentPlacement('tournaments_count'),
            ComponentPlacement('players_count'),
            ComponentPlacement('teams_count'),
        ),
        body=(
            ComponentPlacement('unique_id'),
            ComponentPlacement('visibility'),
            ComponentPlacement('tags'),
            ComponentPlacement('plugin_health'),
        ),
        details=(ComponentPlacement('details'),),
        footer=(ComponentPlacement('actions'),),
    ),
    list=ListLayout(
        columns=(
            ListColumn(
                'identity',
                label=_('Event'),
                width=NAME_COLUMN_WIDTH,
                cell_class=NAME_COLUMN_CELL_CLASS,
            ),
            ListColumn(
                'date_range',
                label=_('Dates'),
            ),
            ListColumn(
                'tags',
                label=_('Tags'),
                width=BADGE_GROUP_COLUMN_WIDTH,
                cell_class=BADGE_GROUP_COLUMN_CELL_CLASS,
            ),
            ListColumn(
                'tournaments_count',
                label=_('Tournaments'),
                header_class='text-center',
                cell_class='justify-content-center',
            ),
            ListColumn(
                'players_count',
                label=_('Players'),
                header_class='text-center',
                cell_class='justify-content-center',
            ),
            ListColumn(
                'event_type',
                label=_('Type'),
                header_class='text-center',
                cell_class='justify-content-center',
            ),
            ListColumn(
                'actions',
                label=_('Actions'),
                header_class='text-end',
                cell_class='justify-content-end',
            ),
        ),
        details=(ComponentPlacement('details'),),
    ),
)
